"use client";

import { motion } from "framer-motion";
import {
  Brain,
  Dumbbell,
  Camera,
  BarChart3,
  ShieldCheck,
  Database,
} from "lucide-react";

const features = [
  {
    title: "AI Coaching Engine",
    text: "Adaptive workout and nutrition logic built around athlete goals.",
    icon: Brain,
  },
  {
    title: "Workout Generator",
    text: "Structured training plans generated by goal, schedule, and focus.",
    icon: Dumbbell,
  },
  {
    title: "Photo Intelligence",
    text: "Upload, compare, and track visual transformation progress.",
    icon: Camera,
  },
  {
    title: "Analytics Dashboard",
    text: "Charts, metrics, assessment history, and progress reports.",
    icon: BarChart3,
  },
  {
    title: "Protected Routes",
    text: "Login, signup, middleware protection, and demo auth flow.",
    icon: ShieldCheck,
  },
  {
    title: "Supabase Backend",
    text: "Cloud database for assessments, workouts, and saved progress.",
    icon: Database,
  },
];

export default function FeaturePanel() {
  return (
    <section className="cinematic-section py-32 px-6 overflow-hidden">
      <div className="section-fade-top" />
      <div className="section-fade-bottom" />
      <div className="absolute inset-0 grid-overlay opacity-20" />

      <div className="relative z-10 max-w-7xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 70 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mb-16"
        >
          <p className="text-blue-300 uppercase tracking-[0.4em] text-sm mb-5">
            Full-Stack Architecture
          </p>

          <h2 className="text-6xl md:text-8xl font-black leading-none">
            SYSTEM
            <span className="block text-blue-400">MODULES</span>
          </h2>

          <p className="text-zinc-400 max-w-2xl mt-8 text-lg">
            A premium AI fitness platform built with real SaaS structure,
            database persistence, protected routes, and advanced interface
            systems.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-6">
          {features.map((feature, i) => {
            const Icon = feature.icon;

            return (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 80 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }}
                whileHover={{ y: -12, scale: 1.02 }}
                viewport={{ once: true }}
                className="glass-panel rounded-[35px] p-8 blue-glow card-shine"
              >
                <Icon className="text-blue-400 mb-8" size={42} />

                <h3 className="text-3xl font-black">
                  {feature.title}
                </h3>

                <p className="text-zinc-400 mt-4 leading-relaxed">
                  {feature.text}
                </p>
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}